### ISSUE TITLE
How many videos left for Kinetics-400？

### ISSUE THREAD

**Issue by bityangke** [activitynet/ActivityNet#38] opened 2019-02-16 09:33 UTC
Hi,
I downloaded Kinetics-400 about 3 months ago, there were:
226797 training videos ;
18689 val videos;
36499 test videos.
Did anybody download Kinetics-400 recently? 
Would it be better to keep an official blacked video-list as Activity-Net dataset?
@cabaf @escorciav @HumamAlwassel 
Thanks very much.

**Comment by bityangke** [comment] 2019-02-16 09:42
For reference, FULL Kinetics-400 about should have:
246535 (8% missed) training videos ;
19907 (6.1% missed) val videos;
38686 (5.7% missed) test videos.

**Comment by VectorYoung** [comment] 2019-02-19 18:31
@bityangke Hi, I just finished downloading the train and val set. The training set has 225425 videos and val has 18932 videos.

**Comment by bityangke** [comment] 2019-02-20 02:50
@VectorYoung Thanks！
But it is weird that your downloaded more val videos than me. I downloaded the dataset three months ago.

**Comment by VectorYoung** [comment] 2019-02-20 17:42
@bityangke Hi, I double checked my videos. The training set is 225023. The val set is 18532. I am wondering will it have a big influence on the performance since so many videos are missed. I am new to video recognition and do not have a concept about that.

**Comment by bityangke** [comment] 2019-02-20 20:03
I believe there will be no big difference.

**Comment by Treenhan** [comment] 2019-03-15 09:34
Hi @VectorYoung, I just wonder how long does it take to download the val set? It took me 1 day to just download about 3GB of data, which I think is abnormal.

**Comment by jeff62802217** [comment] 2019-06-05 10:26
> @bityangke Hi, I just finished downloading the train and val set. The training set has 225425 videos and val has 18932 videos.

HI,have you met the problem that 400 folders is created but nothing is downloaed?

**Comment by escorciav** [comment] 2019-08-30 17:30
Thanks for sharing this. I will close the issue as this repo is related to ActivityNet and the problem is out of our scope.

- Feel free to use the thread to exchange more data.

- If you are interested in a full release of Kinetics videos for academic purposes, please vote up [this thread](https://github.com/activitynet/ActivityNet/issues/28#issuecomment-480499548). It will help

**Closed by escorciav** 2019-08-30 17:30 UTC
