### ISSUE TITLE
can't create environment

### ISSUE THREAD

**Issue by davidkarl** [activitynet/ActivityNet#40] opened 2019-02-26 09:54 UTC
i've tried running condaa env create -f environment.yml but got the following error:

ResolvePackageNotFound:
  - readline==6.2=2
  - ffmpeg==3.1.3=0
  - sqlite==3.13.0=0
  - tk==8.5.18=0
  - zlib==1.2.8=3
  - openssl==1.0.2k=1

Any ideas? :)

**Comment by escorciav** [comment] 2019-03-03 16:05
Thanks for your interest in our work. Are you referring to the YML file for the Kinetics crawler?

If that's the case, I just managed to reproduce it on my end from scratch. My version of conda is `conda 4.5.11`. Note that my machine is Linux-x86_64. I don't know if the all the dependencies are available in osx or Windows.

**Comment by escorciav** [comment] 2019-04-07 11:46
I will close this issue as it has been a while, and we could actually recreate the environment.

**Closed by escorciav** 2019-04-07 11:46 UTC

**Comment by wangwill** [comment] 2019-11-06 14:08
I met the same issue here. 
![image](https://user-images.githubusercontent.com/9379983/68305058-e90b2d00-00f6-11ea-920b-f2ae3aec9be2.png)

**Comment by nch08a** [comment] 2020-03-07 17:35
Just to echo: on a new install of Ubuntu 19.10, conda 4.8.2, I get almost the exact same error:

![image](https://user-images.githubusercontent.com/7951017/76148007-b4d55800-6067-11ea-9672-dcb4c7a0a07f.png)

**Comment by nch08a** [comment] 2020-03-07 18:04
It looks like those particular versions aren't available for my current system through conda.  Given that Python 2.7 is no longer maintained, it would be nice to have an updated environment.yml file.

**Comment by AlexanderMelde** [comment] 2020-04-20 10:18
Take a look at this similar issue: https://github.com/datitran/object_detector_app/issues/41 . It looks like this error is kinda intended by how condas environment files work.

I would also suggest updating the environment file (also because some dependencies are not needed - e.g. i can't find a reference to tk in the code) or changing to a simpler pip install requirements.txt file like the following:

```
decorator==4.0.11
olefile==0.44
youtube-dl==2017.6.5
joblib==0.9.4
numpy==1.12.1
openssl==1.0.2k
pandas==0.19.2
python-dateutil==2.6.0
pytz==2017.2
readline==6.2
setuptools==27.2.0
six==1.10.0
sqlite==3.13.0
tk==8.5.18
wheel==0.29.0
zlib==1.2.8
```

And we should definitely upgrade to Python 3
[![Python3](https://i.redd.it/dbkb061d35w31.png)](https://www.reddit.com/r/ProgrammerHumor/comments/dqadnq/as_a_student_it_really_makes_me_angry/)
